[pytest]
testpaths =
    quantforge
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs =
    backtesting
    scripts
    data
    outputs
    logs
    .git
    .venv
    __pycache__
addopts = --import-mode=importlib
